### ISSUE TITLE
Ubuntu 20.04 build errors (x86):  scalapack

### ISSUE THREAD

**Issue by mattzett** [gemini3d/external#3]
[ 89%] Performing configure step for 'scalapack'
-- The C compiler identification is GNU 9.4.0
-- The Fortran compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /usr/bin/gfortran - skipped
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 - yes
-- checking that C and Fortran compilers can link
-- checking that C and Fortran compilers can link - OK
-- Performing Test HAS_IMPLICIT_FUNC_FLAG
-- Performing Test HAS_IMPLICIT_FUNC_FLAG - Success
-- Could NOT find MPI_C (missing: MPI_C_WORKS) 
-- Could NOT find MPI_Fortran (missing: MPI_Fortran_WORKS) 
CMake Error at /home/parallels/cmake-3.21.2-linux-x86_64/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_Fortran_FOUND C Fortran)
Call Stack (most recent call first):
  /home/parallels/cmake-3.21.2-linux-x86_64/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /home/parallels/cmake-3.21.2-linux-x86_64/share/cmake-3.21/Modules/FindMPI.cmake:1748 (find_package_handle_standard_args)
  CMakeLists.txt:28 (find_package)

**Comment by mattzett** [comment]
All of the mpi libraries appear to be in install-prefix so somehow it isn't picking those up

**Comment by scivision** [comment]
OK this is the broken factory FindMPI not heeding CMAKE_PREFIX_PATH. I will add MPI_ROOT hint

**Comment by scivision** [comment]
I did create a CMake bug report for this. However, since this may affect many or all CMake versions, we'll always have to have in mind to specify MPI_ROOT. https://gitlab.kitware.com/cmake/cmake/-/issues/23375

**Comment by scivision** [comment]
This should be fixed by d8255c7  
Can you let me know if that works?
